<?php
    $footer = $this->getConfig('porto_settings/footer');
?>
<div class="footer">
<?php
    if( $footer['footer_top'] ){
?>
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <?php
                    $area = 'footer_top_block';
                    $type = $footer[$area];
                    if( $type == 'custom' && $footer['footer_top_custom'] ){
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if($block) {
                            $block->setBlockId($footer['footer_top_custom']);
                        }
                        if($block){
                            echo '<div class="custom-block">'.$block->toHtml().'</div>';
                        }
                    }

                ?>
                </div>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_middle'] ){
?>
    <div class="footer-middle">
        <div class="container">
            <div class="row">
            <ul id="menu-footer" class="menu">
                <li class="footer-menu-item">
                    <a href="<?php echo $this->getBaseUrl();?>shop-all">Shop</a>
                </li>
                <li class="footer-menu-item">
                    <a href="<?php echo $this->getBaseUrl();?>customer/account">My Account</a>
                </li>
                <li class="footer-menu-item">
                    <a href="<?php echo $this->getBaseUrl();?>sizing-chart">Size Chart</a>
                </li>
                <li class="footer-menu-item">
                    <a href="<?php echo $this->getBaseUrl();?>shipping-and-returns">Shipping & Returns</a>
                </li>
                <li class="footer-menu-item">
                    <a href="http://www.freewheelchairmission.org" target="_blank">Charity</a>
                </li>
                <li class="footer-menu-item">
                    <a href="<?php echo $this->getBaseUrl();?>contact">Contact Duc</a>
                </li>
                <li class="footer-menu-item">
                    <a href="<?php echo $this->getBaseUrl();?>faq">Help</a>
                </li>
            </ul>  
        </div>
        </div>
        <!-- <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('custom_footer_links')->toHtml();?> -->
    </div>
<?php
    }
    if( $footer['footer_middle_2'] ){
?>
    <div class="footer-middle footer-middle-2">

    </div>
<?php
    }
    if( $footer['footer_bottom'] ){
?>

<?php
    }
?>
</div>